### ISSUE TITLE
Separate `deploy-js` into `minify-js` and `fingerprint-js`and same for `deploy-css`

### ISSUE THREAD

**Issue by agopshi** [loewydesign/loewy-assets#6]
Right now, `deploy-js` both minifies and fingerprints the JS files. Let's separate this into two separate tasks (`minify-js` and `fingerprint-js`). For backwards compatibility, we can keep the `deploy-js` tasks, but it should just run the two new tasks. Please do the same thing for the `deploy-css` task as well.

**Comment by agopshi** [comment]
@dan-ld Check this commit comment here: https://github.com/loewydesign/loewy-assets/commit/01ed34d2d85e6fed1db64839d898aa143d76febe#commitcomment-17756005

**Comment by dan-ld** [comment]
@agopshi Sure. I've updated it to work as you describe in your linked comment. Tasks are now separated and can be run independently or together using the deploy task.
